### ISSUE TITLE
Make diver delete duplicates before evaluating the likelihood

### ISSUE THREAD

**Issue by patscott** [patscott/Diver#2]
At the moment, you can tell Diver to delete duplicate members of the population in a given generation, but it does this _after_ evaluating the target function -- so it wastes time re-evaluating the target for the duplicate points.  The deletion of duplicates needs to be done _before_ the objective function is evaluated.

**Comment by elinoreroebber** [comment]
Makes sense to me (it could be done at the same time as the boundary constraints are imposed), but a couple of points to keep in mind:

- Duplicate vectors should essentially never happen in a jDE run, so it shouldn't be wasting that much time currently.  Duplicates are really only a problem for the "classic DE" best/ or rand/ strategies.

- If you're weeding out duplicates before selection, you'll need to also compare to the previous generation, in case a duplicate gets inherited.

**Comment by patscott** [comment]
Hey @elinoreroebber all my contact deets for you seem to be out of date -- can you shoot me an email?  Best is to get my current details from LinkedIn: https://www.linkedin.com/in/pat-scott/

**Comment by patscott** [comment]
I've just been looking into doing this, and I think it may not actually be a good idea after all.  To weed out duplicates before selection would require an additional `MPI_Allgather` to be added to `selection::selector` in order to distribute all the trial vectors, which constitutes a non-trivial additional performance cost for each generation.  Adding that MPI call would then also make the `removeDuplicates` option incompatible with the `discard_unfit_points` option introduced in #4, as `discard_unfit_points` runs `selection::selector` in a loop that may execute a different number of times for each process (which is what makes `discard_unfit_points` likely incompatible with any objective functions that have MPI calls, btw).   One could add extra checks that made the duplicate removal happen either in `selection::selector` or `selection::replace_generation` depending on whether `discard_unfit_points` is in use or not, but personally I think that at that point, the advantage gleaned from *sometimes* avoiding a few unnecessary objective evaluations is probably offset by the additional code complexity that would bring.

Thoughts @elinoreroebber?

**Comment by elinoreroebber** [comment]
That's a good point. I think that given that diver's pretty much exclusively being run using jDE or lambdajDE strategies, it's probably not worth the extra code complexity, and it's definitely not worth a performance hit.

It's not mathematically impossible to have duplicate vectors in those modes, but since each trial vector has its own randomly-generated float for the scaling factor F (and additional scaling factor lambda in the latter case), it's extremely unlikely. I recall it happening when there was some kind of problem with MPI, but not otherwise. Although of course you have more experience than me running it in production!

**Comment by patscott** [comment]
Cool, thanks - closing now then.
